# Generated by Django 5.1.4 on 2025-02-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailconfirmationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
