# Generated by Django 5.1.4 on 2025-02-20 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
