# Generated by Django 5.1 on 2024-12-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('Опубликована', 'Опубликована'), ('Черновик', 'Черновик')], default='Черновик', max_length=20),
        ),
    ]
